// Códigos Sagrados — contenido (fuente: PDFs de Gilda). Estructura abierta: para añadir
// una categoría o un código basta editar este archivo; la UI se genera sola.
window.CODIGOS_DATA = { categorias: [
{ key:'amor', nombre:'Amor', sub:'Atraer, sanar y fortalecer el amor', color:'#e79ab4', palo:'copas', codigos:[
  {c:'82412', p:'Atraer a la persona correcta y adecuada para ti, favoreciendo una relación alineada con tu bienestar'},
  {c:'715400', p:'Favorecer el regreso del ser amado o una posible reconciliación'},
  {c:'802', p:'Activar las feromonas'},
  {c:'11834', p:'Aumentar la libido'},
  {c:'904', p:'Potenciar el atractivo sexual'},
  {c:'111', p:'El código de la sexualidad'},
  {c:'739', p:'Solucionar problemas sexuales en la pareja'},
  {c:'1021', p:'Tranquilizar a una persona cuando existe una discusión o conflicto sentimental'},
  {c:'889', p:'Pedir perdón o ser perdonado'},
  {c:'75139', p:'Despejar caminos en el amor'},
  {c:'11550', p:'Atraer el amor de tu vida'},
  {c:'70', p:'Invocar el ángel del amor'},
  {c:'571', p:'Facilitar la conexión entre almas gemelas'},
  {c:'580', p:'Para que empiece en ti y te busque; hablar desde el amor con tu pareja'},
  {c:'191919', p:'Atraer velozmente al compañero de vida'},
  {c:'25700', p:'Cumplir deseos en el amor'},
  {c:'390', p:'Superar obstáculos en el amor'},
  {c:'725', p:'Reconciliarse, regresar con tu ex, restaurar parejas rotas'},
  {c:'159', p:'Soltar emociones intensas en la relación'},
  {c:'781', p:'Romper bloqueos para que llegue el alma gemela'},
  {c:'672', p:'Romper cadenas, llenar carencias y sanar el corazón'},
  {c:'216', p:'Sanar resentimientos en una relación'},
  {c:'877', p:'Amor propio'},
  {c:'31', p:'Activar la fidelidad en tu relación'},
  {c:'1751', p:'Milagro inesperado y rápido en el amor'},
  {c:'541', p:'Aumentar el amor en pareja'},
  {c:'718', p:'Reconciliación con tu pareja o en una relación'},
  {c:'62987', p:'Romper el orgullo de esa persona para poder hablar con ella'},
  {c:'35133', p:'Enviar un "te amo" a una persona'},
  {c:'2190', p:'Éxito en el amor'},
  {c:'0447', p:'Un nuevo comienzo en el amor'},
  {c:'212', p:'Evitar la infidelidad'},
  {c:'2026', p:'Apresurar la llegada de un alma gemela o afín a ti'},
  {c:'2526', p:'Atraer el amor'},
  {c:'2918', p:'Felicidad inmediata'},
  {c:'620', p:'Alegría, felicidad y amor; sanar una herida de amor'},
  {c:'51826', p:'Activar los rayos de la estrella secreta del amor para hacer tus sueños realidad'},
  {c:'294', p:'Fortalecer el amor de pareja'},
  {c:'61126', p:'Recibir el amor a todos los niveles, sobre todo cuando no te sientes amado'},
  {c:'427', p:'Amor'},
  {c:'863', p:'Ángel femenino del amor'},
  {c:'219', p:'Aprender las leyes de la atracción y del amor'},
  {c:'125', p:'Solucionar problemas en el amor'} ] },

{ key:'dinero', nombre:'Dinero y trabajo', sub:'Abundancia, empleo y prosperidad', color:'#ecc874', palo:'oros', codigos:[
  {c:'71588', p:'Atraer clientes a un negocio'},
  {c:'42170', p:'Dinero y abundancia sin tropiezos'},
  {c:'741', p:'Solución inmediata en problemas económicos o laborales'},
  {c:'199', p:'Ganar la lotería y juegos de azar'},
  {c:'344', p:'Lograr lo imposible restaurando la energía del dinero o el trabajo'},
  {c:'7131', p:'Encontrar el empleo ideal, que llegue con facilidad y rapidez'},
  {c:'25700', p:'Cumplir un deseo económico o laboral'},
  {c:'390', p:'Superar obstáculos en el dinero o en lo laboral'},
  {c:'520', p:'Recibir dinero inesperado'},
  {c:'300', p:'Sanar el miedo al dinero'},
  {c:'773', p:'Liberarse de espíritus de ruina y miseria'},
  {c:'294', p:'Sanar el miedo al éxito'},
  {c:'897', p:'Para que el dinero fluya hacia ti, sin tropiezos'},
  {c:'47620', p:'Conectar con el dinero'},
  {c:'61316', p:'Disolver de raíz los implantes que impiden la conexión con la energía del dinero'},
  {c:'858', p:'Para que te paguen deudas; recuperar dinero'},
  {c:'4000000', p:'Sanar la relación con el dinero a nivel subconsciente'},
  {c:'2190', p:'Éxito en el dinero y en el trabajo'},
  {c:'0447', p:'Un nuevo comienzo laboral o económico'},
  {c:'744', p:'Restaurar situaciones extremas o casos donde ya no sentías solución económica o laboral'},
  {c:'212', p:'Conseguir mentores en finanzas que te enseñen el manejo correcto del dinero'},
  {c:'1016', p:'Traer dinero de la energía del sol'},
  {c:'1122', p:'Para que el dinero fluya hacia ti'},
  {c:'425', p:'Dinero'},
  {c:'888', p:'Protección para el dinero y lo laboral'},
  {c:'33300', p:'Atraer oportunidades laborales urgentes'},
  {c:'11111', p:'Abrir caminos laborales'},
  {c:'55500', p:'Acelerar cambios positivos en el trabajo'},
  {c:'88888', p:'Atraer abundancia económica'},
  {c:'71717', p:'Conectar con el empleo ideal'},
  {c:'99900', p:'Mejorar ingresos y estabilidad'},
  {c:'44444', p:'Seguridad laboral y éxito'},
  {c:'12345', p:'Desbloquear oportunidades económicas'},
  {c:'22222', p:'Acuerdos laborales armoniosos'} ] },

{ key:'salud', nombre:'Salud', sub:'Sanación y bienestar del cuerpo', color:'#86cf9e', palo:'bastos', codigos:[
  {c:'25300', p:'Liberar de cualquier enfermedad contagiosa'},
  {c:'1751', p:'Milagro inesperado y rápido en la salud'},
  {c:'81621', p:'Restaurar el ADN para la salud'},
  {c:'50', p:'Reconectar el ADN con las doce hebras que ayudan a sanar y restaurar el cuerpo'},
  {c:'464', p:'Autosanación del cuerpo'},
  {c:'128', p:'Sanación a todos los niveles en cuestión de salud'},
  {c:'25700', p:'Cumplir deseos en la salud o en su mejora'},
  {c:'110834', p:'Hacer una sanación a distancia'},
  {c:'1297', p:'Fortalecer la mente'},
  {c:'34', p:'Sanar dolor emocional'},
  {c:'45600', p:'Borrar memorias negativas'},
  {c:'2516', p:'Sanar karmas sexuales'},
  {c:'71566', p:'Liberar del alcoholismo'},
  {c:'554', p:'Sanar la codependencia'},
  {c:'1015', p:'Sanar los celos'},
  {c:'2539', p:'Sanar el asma'},
  {c:'525700', p:'Sanar ataques de pánico'},
  {c:'122714', p:'Sanar la drogadicción'},
  {c:'154', p:'Dejar de fumar marihuana'},
  {c:'811', p:'Dejar de fumar'},
  {c:'1188', p:'Prevenir el cáncer'},
  {c:'1577', p:'Cáncer; cáncer de vejiga'},
  {c:'29700', p:'Cáncer de colon'},
  {c:'2194', p:'Cáncer testicular'},
  {c:'52569', p:'Resolver problemas en el embarazo'},
  {c:'1449', p:'Disfrutar el embarazo'} ] },

{ key:'limpieza', nombre:'Limpieza y protección energética', sub:'Escudo, limpieza y liberación', color:'#8db0ec', palo:'espadas', codigos:[
  {c:'450', p:'Protección'},
  {c:'828', p:'Favorecer un descanso reparador y restaurar tu energía'},
  {c:'051', p:'Eliminar enemigos ocultos'},
  {c:'0927', p:'Eliminar vibraciones negativas y la influencia de objetos, personas o entidades negativas; limpiar espacios'},
  {c:'44', p:'Sanar y liberar de raíz la influencia de magia negra, amarres y trabajos'},
  {c:'2579', p:'Ser inmune a maldiciones'},
  {c:'8585', p:'Protección contra magia negra'},
  {c:'1021', p:'Tranquilizar a una persona cuando existe un problema o conflicto en una relación'},
  {c:'79', p:'Favorecer el desbloqueo de la prosperidad en las relaciones'},
  {c:'615', p:'Protección contra envidias'},
  {c:'525', p:'Activar la protección de tu ángel de la guarda'},
  {c:'921', p:'Invocar el escudo del Arcángel Miguel: protección y limpieza energética'},
  {c:'128', p:'Sanación a todos los niveles'},
  {c:'110834', p:'Hacer una sanación a distancia'},
  {c:'715', p:'Casa sana'},
  {c:'1617', p:'Quitar brujería'},
  {c:'41933', p:'Energía de Jesús para limpiar'},
  {c:'791', p:'Cancelar el karma; sanar vidas pasadas y abrir caminos en felicidad y prosperidad'},
  {c:'2516', p:'Cancelar karma sexual'},
  {c:'554', p:'Soltar y dejar fluir; anular resistencias y frenos que no te permiten avanzar'},
  {c:'457', p:'Eliminar bloqueos'},
  {c:'215', p:'Romper cadenas'},
  {c:'3314', p:'Liberar cadenas de cualquier tipo que impiden tu crecimiento energético'},
  {c:'159', p:'Soltar emociones intensas; alegría de vivir'},
  {c:'505', p:'Espíritus milagrosos'},
  {c:'18', p:'Fuerza, seguridad y paz'},
  {c:'72988', p:'Salir de un lugar o relación donde ya no se desea estar'},
  {c:'530', p:'Evitar daños por parte de vecinos'},
  {c:'314', p:'Terminar o evitar amistades nocivas'},
  {c:'455', p:'Protección contra fuerzas siniestras'},
  {c:'52919', p:'Eliminar de tu existencia las entidades negativas almacenadas en tu ser'},
  {c:'339', p:'Liberar la culpa de haber hecho amarres'},
  {c:'553', p:'Sanar el árbol genealógico'},
  {c:'69900', p:'Mal de ojo y envidias'},
  {c:'443355', p:'Invocar al Espíritu Santo para liberar lazos kármicos que perjudican esta y otras vidas'},
  {c:'1221', p:'Quitar entidades negativas del cuerpo, tuyas o de otra persona, que causen dolor'},
  {c:'425', p:'Limpiar la energía del dinero'},
  {c:'825', p:'Activar tu seguridad energética'},
  {c:'11129', p:'Que una persona que te molesta o envidia se aleje'},
  {c:'593', p:'Evitar daños de terceras personas hacia ti'},
  {c:'694', p:'Neutralizar la envidia'},
  {c:'237', p:'Eliminar frecuencias negativas del bajo astral'},
  {c:'860907', p:'Transformar cualquier bloqueo en tu vida'},
  {c:'1188', p:'Liberar lazos kármicos de vidas pasadas y actuales'},
  {c:'26700', p:'Limpiar el camino energético; limpiar el aura'},
  {c:'12900', p:'Librar de cualquier espíritu maligno que rodee a la persona o su casa'},
  {c:'111111', p:'Liberar trabajos de magia negra del pasado y del presente'},
  {c:'212', p:'Liberar la energía de venganza de vidas pasadas'},
  {c:'1579', p:'Romper lazos y cadenas kármicas de vidas pasadas y actuales'},
  {c:'1118', p:'Liberar implantes negativos'},
  {c:'1', p:'Paz interior'},
  {c:'594', p:'Limpieza del aura'},
  {c:'19913', p:'Cerrar el aura ante cualquier energía negativa'},
  {c:'811', p:'Reparar el aura de cualquier daño'},
  {c:'72599', p:'Sanar el aura'},
  {c:'729', p:'Retirar dardos, balas y flechas de entidades negativas; paz mental y equilibrio interior'},
  {c:'11111111', p:'Proteger y liberar de trabajos y magia negra superpoderosa'},
  {c:'93', p:'Santa Filomena: protección de accidentes y de la oscuridad'},
  {c:'570', p:'Liberación de adicciones y dependencias'},
  {c:'333', p:'Protección y asistencia espiritual'},
  {c:'719', p:'Sanación emocional profunda'},
  {c:'1122', p:'Romper patrones repetitivos'},
  {c:'4418', p:'Transmutación de energía negativa'},
  {c:'71588', p:'Fortaleza espiritual y voluntad'},
  {c:'897', p:'Limpieza energética emocional'},
  {c:'1810', p:'Recuperar control personal y claridad'},
  {c:'519834', p:'Corte de lazos energéticos'},
  {c:'888', p:'Transmutación y liberación profunda; restaurar el equilibrio energético'},
  {c:'1111', p:'Apertura de caminos y nuevos comienzos'},
  {c:'2121', p:'Soltar relaciones que ya no corresponden'},
  {c:'29', p:'Liberación emocional'},
  {c:'33300', p:'Limpieza profunda de trabajos de magia negra'},
  {c:'44400', p:'Protección divina contra ataques energéticos negativos'},
  {c:'71500', p:'Romper hechizos, amarres y manipulaciones'},
  {c:'99900', p:'Transmutar energía negativa en luz'},
  {c:'777', p:'Protección espiritual'},
  {c:'1212', p:'Cerrar portales energéticos negativos'},
  {c:'43200', p:'Cortar lazos energéticos dañinos'},
  {c:'000', p:'Reset energético total'},
  {c:'2020', p:'Limpiar karmas energéticos negativos'},
  {c:'77777', p:'Protección divina máxima'},
  {c:'55500', p:'Liberación de cargas energéticas densas'} ] },

{ key:'varios', nombre:'Varios', sub:'Familia, hogar, sanación interior…', color:'#cdbdf2', palo:'copas', codigos:[
  {c:'288', p:'Eliminar y sanar traumas de la infancia y adolescencia'},
  {c:'999', p:'Arcángeles: justicia divina'},
  {c:'1297', p:'Fortalecer la mente'},
  {c:'34', p:'Sanar dolor emocional'},
  {c:'41933', p:'Atraer la energía de Jesús'},
  {c:'159', p:'Soltar emociones intensas'},
  {c:'554', p:'Soltar y dejar fluir; recibir lo que el universo tiene para ti'},
  {c:'928', p:'Vencer el miedo a la muerte'},
  {c:'681', p:'Vencer miedos irracionales'},
  {c:'294', p:'No sabotearte'},
  {c:'812', p:'Sanar experiencias dolorosas'},
  {c:'224', p:'Sanar cuando se tienen hijos no deseados o si fuiste un hijo no deseado'},
  {c:'378', p:'Sanar el abuso sexual sufrido en la infancia; tener buen futuro'},
  {c:'108', p:'Sanación de carencias afectivas en la infancia'},
  {c:'843', p:'Sanación de la sexualidad'},
  {c:'613', p:'Sanar y quitar el sufrimiento de abuso sexual en la infancia'},
  {c:'525', p:'Ángel de la Guarda'},
  {c:'5772', p:'Cortar lazos con exparejas'},
  {c:'577', p:'Cortar lazos telepáticos con exparejas'},
  {c:'344', p:'Lograr lo imposible; activar en casos imposibles'},
  {c:'25700', p:'Cumplir un deseo'},
  {c:'877', p:'Amor propio'},
  {c:'45600', p:'Borrar memorias negativas'},
  {c:'545', p:'Recibir del universo energía para tus líneas de vida'},
  {c:'91', p:'Para que se arrepienta del daño que te hicieron'},
  {c:'100', p:'Aprender a decir no cuando así se necesite'},
  {c:'7278', p:'Sanar almas adictas al sufrimiento'},
  {c:'102', p:'Angustia'},
  {c:'363', p:'Ansiedad'},
  {c:'154', p:'Sanar la herida de abandono'},
  {c:'314', p:'Sanar la herida de humillación'},
  {c:'907', p:'Sanar la herida de injusticia'},
  {c:'260', p:'Sanar la herida de rechazo'},
  {c:'218', p:'Sanar heridas de traición'},
  {c:'527', p:'Encorazonar con la energía celestial'},
  {c:'825', p:'Obtener seguridad'},
  {c:'169', p:'Aliviar el sentimiento de soledad'},
  {c:'451', p:'Tener seguridad en uno mismo'},
  {c:'28500', p:'Abrir posibilidades'},
  {c:'4', p:'Arcángel Uriel: éxito, seguridad y confianza en uno mismo'},
  {c:'17', p:'Ángel de la gratitud'},
  {c:'144', p:'Protección y guía para los hijos'},
  {c:'721', p:'Unión de madre, padre e hijos'},
  {c:'1010', p:'Armonía y equilibrio familiar'},
  {c:'420', p:'Paz en el hogar'},
  {c:'318', p:'Resolver conflictos'} ] }
]};
