// Oráculo diario — contenido (fuente: PDFs de Gilda). Estructura abierta: para añadir un
// oráculo nuevo basta agregar un objeto a `oraculos` (la UI se genera sola).
window.ORACULO_DATA = { oraculos: [
{ key:'alma', nombre:'Lo que su alma desea decirte', sub:'Mensajes que esa persona guarda en silencio', color:'#cdbdf2', palo:'copas', tipo:'frase',
  cartas:[
  'No he podido olvidarte.','Pienso en ti más de lo que imaginas.','Comprendí tu valor cuando ya no estabas.','Me arrepiento de muchas cosas.','Quisiera volver a hablar contigo.','Sigo sintiendo una conexión contigo.','Aún ocupas un lugar en mi corazón.','El orgullo me mantiene en silencio.','Extraño tu presencia.','Sueño contigo con frecuencia.',
  'No fue fácil dejarte ir.','Quisiera saber cómo estás.','Todavía guardo esperanza.','Estoy sanando mis heridas.','Necesito tiempo para cambiar.','Quiero pedirte perdón.','Me cuesta expresar lo que siento.','Hay palabras que nunca te dije.','Me haces mucha falta.','Tu recuerdo sigue vivo en mí.',
  'Nadie ha logrado reemplazarte.','Me di cuenta de mis errores.','Ojalá hubiera actuado diferente.','A veces deseo empezar de nuevo.','Estoy luchando contra mis miedos.','La distancia me hizo reflexionar.','Nunca dejé de preocuparme por ti.','Me duele haberte lastimado.','Sigo aprendiendo gracias a nuestra historia.','Quisiera que el destino nos reúna otra vez.',
  'Hay algo pendiente entre nosotros.','Mi corazón aún te recuerda.','No todo está perdido.','Estoy reuniendo valor para acercarme.','Aún siento amor por ti.','Te extraño en silencio.','El tiempo cambió mi forma de verte.','Cada recuerdo me acerca a ti.','Espero que aún haya una oportunidad.','No he encontrado lo que tenía contigo.',
  'Mi silencio no significa indiferencia.','Te llevo en mis pensamientos.','Siento que aún estamos conectados.','Gracias por todo lo que vivimos.','Siempre ocuparás un lugar especial en mí.','Me gustaría sanar esta historia contigo.','Estoy listo para dejar atrás el pasado.','El universo sigue cruzando nuestros caminos.','Confío en que el destino hará lo correcto.','Aún no he dicho la última palabra.'
  ].map(function(m,i){ return { id:i+1, mensaje:m }; }) },

{ key:'sentimental', nombre:'Situación sentimental', sub:'La energía que rodea tu corazón hoy', color:'#e79ab4', palo:'copas', tipo:'titulo',
  cartas:[
  {t:'Reencuentro', kw:'Regreso, destino, oportunidad, conexión', m:'Hay una nueva oportunidad para aquello que parecía terminado.'},
  {t:'Distancia', kw:'Espacio, reflexión, pausa, espera', m:'El tiempo es necesario para que las emociones encuentren claridad.'},
  {t:'Comunicación', kw:'Conversación, mensaje, sinceridad, verdad', m:'Lo que permanece en silencio pronto buscará ser expresado.'},
  {t:'Sanación', kw:'Perdón, calma, liberación, crecimiento', m:'Antes de amar plenamente, el corazón necesita sanar.'},
  {t:'Destino', kw:'Sincronía, aprendizaje, camino, propósito', m:'Nada ocurre por casualidad; esta conexión tiene un propósito.'},
  {t:'Confusión', kw:'Dudas, indecisión, incertidumbre, bloqueo', m:'Las respuestas llegarán cuando las emociones se tranquilicen.'},
  {t:'Atracción', kw:'Deseo, química, magnetismo, pasión', m:'Existe una energía que sigue acercándolos.'},
  {t:'Cambio', kw:'Transformación, evolución, movimiento, renovación', m:'Lo que hoy conoces pronto tomará un rumbo diferente.'},
  {t:'Paciencia', kw:'Espera, confianza, proceso, tiempo', m:'No fuerces los acontecimientos; todo tiene su momento.'},
  {t:'Compromiso', kw:'Estabilidad, unión, responsabilidad, futuro', m:'La relación puede fortalecerse si ambos están dispuestos.'},
  {t:'Liberación', kw:'Cierre, desapego, paz, independencia', m:'Soltar abrirá espacio para algo mejor.'},
  {t:'Reciprocidad', kw:'Equilibrio, correspondencia, cariño, armonía', m:'Lo que entregas también puede regresar a ti.'},
  {t:'Esperanza', kw:'Fe, ilusión, confianza, luz', m:'No todo está perdido; aún hay posibilidades.'},
  {t:'Nostalgia', kw:'Recuerdos, pasado, añoranza, emociones', m:'Alguien sigue pensando en lo vivido.'},
  {t:'Verdad', kw:'Sinceridad, revelación, claridad, honestidad', m:'Una verdad importante saldrá a la luz.'},
  {t:'Decisión', kw:'Elección, determinación, cambio, acción', m:'Ha llegado el momento de elegir un camino.'},
  {t:'Renacer', kw:'Nuevos comienzos, oportunidad, evolución, esperanza', m:'Después de la tormenta nace una nueva etapa.'},
  {t:'Encuentro', kw:'Cita, acercamiento, coincidencia, conexión', m:'El destino prepara un momento importante.'},
  {t:'Protección', kw:'Guía, apoyo, seguridad, confianza', m:'No estás solo; hay fuerzas que cuidan este proceso.'},
  {t:'Miedo', kw:'Inseguridad, heridas, defensa, resistencia', m:'El temor puede estar impidiendo avanzar.'},
  {t:'Perdón', kw:'Reconciliación, comprensión, paz, liberación', m:'Perdonar cambia el rumbo del corazón.'},
  {t:'Espera', kw:'Paciencia, calma, maduración, confianza', m:'Lo que buscas necesita más tiempo.'},
  {t:'Ilusión', kw:'Sueños, optimismo, posibilidades, alegría', m:'Permítete creer nuevamente en el amor.'},
  {t:'Aprendizaje', kw:'Experiencia, crecimiento, evolución, sabiduría', m:'Cada relación deja una enseñanza valiosa.'},
  {t:'Reconexión', kw:'Regreso, vínculo, acercamiento, oportunidad', m:'Los caminos pueden volver a unirse.'},
  {t:'Silencio', kw:'Introspección, pausa, observación, reflexión', m:'No confundas el silencio con la falta de interés.'},
  {t:'Lealtad', kw:'Fidelidad, confianza, estabilidad, respeto', m:'La sinceridad será la base de esta conexión.'},
  {t:'Tentación', kw:'Deseo, impulso, atracción, elección', m:'No todo lo que atrae conduce al bienestar.'},
  {t:'Abundancia', kw:'Plenitud, bienestar, felicidad, prosperidad', m:'El amor florece cuando también floreces tú.'},
  {t:'Intuición', kw:'Señales, percepción, sabiduría, guía interior', m:'Tu corazón ya conoce la respuesta.'},
  {t:'Reconciliación', kw:'Perdón, regreso, oportunidad, unión', m:'Existe la posibilidad de reparar lo que se rompió.'},
  {t:'Límites', kw:'Respeto, autoestima, equilibrio, protección', m:'Amar también significa poner límites sanos.'},
  {t:'Valor', kw:'Autoestima, confianza, fortaleza, dignidad', m:'Reconoce lo mucho que vales.'},
  {t:'Sorpresa', kw:'Noticias, cambio, inesperado, alegría', m:'Algo que no esperabas puede transformar la situación.'},
  {t:'Claridad', kw:'Certeza, comprensión, verdad, enfoque', m:'Las dudas comenzarán a disiparse.'},
  {t:'Pasión', kw:'Intensidad, deseo, química, emoción', m:'La atracción sigue viva.'},
  {t:'Elección del corazón', kw:'Sentimientos, decisión, autenticidad, amor', m:'Escucha lo que realmente siente tu corazón.'},
  {t:'Ciclo cerrado', kw:'Final, aceptación, renovación, paz', m:'Para recibir algo nuevo, primero debes cerrar una etapa.'},
  {t:'Conexión espiritual', kw:'Alma, destino, aprendizaje, vínculo', m:'Existe un lazo que trasciende lo evidente.'},
  {t:'Esperanza renovada', kw:'Optimismo, oportunidad, fe, renacer', m:'El universo abre un nuevo camino para ti.'},
  {t:'Corazón abierto', kw:'Confianza, entrega, amor, vulnerabilidad', m:'Permítete recibir el amor que mereces.'},
  {t:'Equilibrio', kw:'Armonía, reciprocidad, estabilidad, paz', m:'Cuando ambas energías se equilibran, el amor fluye.'},
  {t:'Nuevos horizontes', kw:'Cambio, oportunidades, expansión, futuro', m:'Lo mejor puede llegar desde donde menos lo imaginas.'},
  {t:'Manifestación', kw:'Intención, creación, energía, propósito', m:'Tus pensamientos y acciones están dando forma a tu realidad.'},
  {t:'Amor verdadero', kw:'Autenticidad, compromiso, respeto, plenitud', m:'El amor que permanece es el que nace desde la verdad.'}
  ].map(function(c,i){ return { id:i+1, titulo:c.t, claves:c.kw, mensaje:c.m }; }) },

{ key:'contacto', nombre:'Energías del contacto cero', sub:'Lo que se mueve mientras no hay contacto', color:'#8db0ec', palo:'espadas', tipo:'frase',
  cartas:[
  'El contacto cero está por romperse.','Se acerca una comunicación.','Hay sentimientos que siguen vivos.','La distancia es solo temporal.','La energía comienza a cambiar.','La otra persona piensa en ti.','El universo está moviendo las piezas.','Se aproxima un reencuentro.','Hay asuntos pendientes.','La conexión sigue activa.',
  'El silencio terminará pronto.','Una conversación traerá claridad.','Se abre una nueva oportunidad.','La reconciliación es posible.','Los bloqueos comienzan a desaparecer.','La verdad saldrá a la luz.','Ambos están aprendiendo una lección.','El tiempo juega a tu favor.','La paciencia dará frutos.','No todo está perdido.',
  'Una señal confirmará tus dudas.','La energía del amor sigue presente.','Es momento de confiar.','Algo inesperado cambiará la situación.','La conexión necesita sanar.','Se están cerrando viejas heridas.','El destino aún no escribe el final.','Habrá un cambio importante.','La otra persona está reflexionando.','El orgullo está perdiendo fuerza.',
  'El miedo retrasa el acercamiento.','La energía favorece el diálogo.','La respuesta llegará cuando menos lo esperes.','Es momento de soltar el control.','Todo ocurre en el momento perfecto.','El universo te está protegiendo.','Esta historia aún tiene algo que enseñar.','Tu paz es la prioridad.','La separación tenía un propósito.','Lo que es para ti encontrará el camino.',
  'Se aproxima un nuevo comienzo.','Hay una decisión importante por tomar.','Una nueva etapa está por iniciar.','La energía favorece el perdón.','El amor propio transformará esta conexión.','Si esta persona no regresa, llegará alguien mejor para ti.','El cierre de este ciclo abrirá una puerta más grande.','Tu corazón volverá a sonreír.','Confía en el camino que el universo está trazando.','Lo mejor para tu alma está cada vez más cerca.'
  ].map(function(m,i){ return { id:i+1, mensaje:m }; }) },

{ key:'tiempo', nombre:'El Tiempo Sagrado', sub:'Cuándo llegará lo que esperas', color:'#ecc874', palo:'oros', tipo:'titulo',
  cartas:[
  {t:'Está más cerca de lo que imaginas', m:'La energía ya comenzó a moverse, aunque todavía no puedas verlo. Lo que esperas está acercándose paso a paso. Mantén la confianza y no permitas que la impaciencia te haga abandonar el camino justo antes de recibir lo que tanto has esperado.'},
  {t:'En pocos días', m:'Los próximos días traerán noticias, movimientos o señales importantes. Mantente atento, porque una pequeña acción o una conversación pueden marcar el inicio del cambio que estabas esperando.'},
  {t:'El tiempo divino', m:'No existe el retraso cuando el universo está preparando el mejor resultado para ti. Todo llegará exactamente cuando pueda sostenerse en tu vida. Confía en el proceso; cada día te acerca más a tu propósito.'},
  {t:'Cuando sueltes el control', m:'Mientras intentes controlar cada detalle, la energía encontrará resistencia. Permite que el universo haga su parte. Soltar no significa renunciar; significa confiar en que lo correcto encontrará el camino hacia ti.'},
  {t:'La espera está llegando a su fin', m:'Has recorrido una etapa de paciencia, aprendizaje y crecimiento. Esa espera está terminando y muy pronto comenzarás a ver resultados concretos. Mantén tu corazón abierto para recibirlos.'},
  {t:'El universo ya está moviendo las piezas', m:'Aunque hoy no puedas verlo, situaciones, personas y oportunidades ya se están acomodando a tu favor. Lo que parecía detenido está cobrando fuerza detrás del escenario.'},
  {t:'No vale la pena seguir esperando', m:'Esta carta te invita a recuperar tu poder. No detengas tu vida esperando que alguien cambie o regrese. Cuando eliges avanzar, el universo abre caminos mucho más grandes de los que imaginabas.'},
  {t:'El destino nunca llega tarde', m:'Lo que está destinado para ti no puede perderse. Si algo aún no ocurre, es porque todavía se está preparando el momento perfecto. Confía: lo que es para tu mayor bien siempre encuentra la forma de llegar.'},
  {t:'Antes de que termine este mes', m:'La energía se está acelerando y los acontecimientos comenzarán a tomar forma muy pronto. Antes de que finalice este ciclo, recibirás una señal, una respuesta o un movimiento que te ayudará a comprender que todo está avanzando.'},
  {t:'El próximo mes traerá movimiento', m:'Lo que hoy parece inmóvil empezará a transformarse. El próximo mes abrirá puertas, traerá noticias o pondrá frente a ti nuevas oportunidades. Mantente dispuesto a recibir los cambios.'},
  {t:'Dentro de tres meses', m:'El universo necesita un poco más de tiempo para acomodar las circunstancias. No interpretes esta espera como un rechazo; es parte de la preparación para que lo que llegue sea estable y duradero.'},
  {t:'Dentro de seis meses', m:'Se está desarrollando un proceso profundo. Durante este tiempo habrá aprendizajes, cambios internos y situaciones que te prepararán para recibir aquello que hoy estás preguntando.'},
  {t:'El momento perfecto ya se está acercando', m:'Quizá todavía no veas resultados, pero la energía ya comenzó a moverse. Cada día te acerca más a aquello que tanto has esperado. La paciencia pronto dará paso a la manifestación.'},
  {t:'Solo falta un último paso', m:'Has avanzado más de lo que imaginas. Antes de que todo se manifieste, será necesario dar un pequeño paso, tomar una decisión o cerrar un asunto pendiente. Después de eso, el camino se abrirá.'},
  {t:'Primero debes cerrar un ciclo', m:'El universo no puede llenar una mano que aún se aferra al pasado. Libera lo que ya cumplió su propósito y deja espacio para recibir lo nuevo. El cierre de hoy será el comienzo de mañana.'},
  {t:'La respuesta llegará cuando menos lo esperes', m:'Cuando dejes de mirar el reloj y de buscar señales a cada instante, la vida te sorprenderá. Muchas de las mejores manifestaciones llegan cuando recuperamos la calma y permitimos que todo fluya.'},
  {t:'Una señal confirmará el momento', m:'No tendrás que adivinar cuándo actuar. El universo pondrá frente a ti una sincronía, una conversación, un sueño o una coincidencia que disipará tus dudas. Confía en tu intuición cuando esa señal aparezca.'},
  {t:'Todo se está alineando a tu favor', m:'Aunque algunas piezas todavía parezcan fuera de lugar, todo está encontrando su sitio. Lo que hoy parece una demora es, en realidad, una preparación para que recibas exactamente lo que necesitas.'},
  {t:'El tiempo de la cosecha', m:'Has sembrado más de lo que imaginas. Cada esfuerzo, cada aprendizaje y cada paso que has dado están creando el momento perfecto para recoger los frutos. La cosecha llega cuando está madura, no cuando la impaciencia la reclama. Muy pronto verás cómo aquello que sembraste empieza a manifestarse.'},
  {t:'El reloj del universo', m:'No todo depende de tu esfuerzo. Existen sincronías, encuentros y circunstancias que deben coincidir para que aquello que deseas pueda manifestarse. El universo está moviendo piezas que aún no alcanzas a ver. Confía en que cada acontecimiento llegará exactamente cuando deba llegar.'},
  {t:'La espera consciente', m:'Esperar no significa detener tu vida. Mientras aquello que anhelas llega, el universo te invita a seguir creciendo, disfrutando y construyendo nuevos caminos. Cuando el momento llegue, descubrirás que la espera también fue parte del regalo.'},
  {t:'Un paso más', m:'Estás mucho más cerca de lo que imaginas. A veces el mayor cambio sucede justo antes de que todo se manifieste. No abandones el camino ahora; un pequeño paso más puede marcar la diferencia entre rendirte y alcanzar aquello que tanto has esperado.'},
  {t:'El tiempo de soltar', m:'Hay momentos en los que el universo responde cuando dejas de controlar el resultado. Soltar no es renunciar; es confiar en que lo que es para ti encontrará la forma de llegar. Al liberar la ansiedad, permites que la energía fluya con mayor facilidad.'},
  {t:'Todo tiene su estación', m:'Así como la naturaleza tiene primavera, verano, otoño e invierno, tu vida también atraviesa ciclos. No intentes adelantar una etapa que todavía necesita madurar. Honra el momento en el que estás, porque cada estación tiene una enseñanza y un propósito.'},
  {t:'El momento indicado', m:'No será antes ni después. Lo que está destinado para ti llegará cuando las condiciones sean las adecuadas para que puedas recibirlo plenamente. Lo que hoy parece tardanza, mañana tendrá todo el sentido. El tiempo correcto siempre trae las mejores versiones de los sueños.'},
  {t:'La sincronía perfecta', m:'Nada ocurre por casualidad. Las personas, las oportunidades y los cambios llegan cuando su presencia puede transformar tu camino. Aunque hoy no lo percibas, el universo está sincronizando cada detalle para que todo suceda de la mejor manera.'},
  {t:'El tiempo de la transformación', m:'Antes de recibir aquello que deseas, tú también estás cambiando. El universo está fortaleciendo tu corazón, ampliando tu visión y preparándote para sostener lo que viene. La transformación es parte del regalo.'},
  {t:'La puerta se abrirá', m:'Puede parecer que todo permanece inmóvil, pero la puerta correcta está a punto de abrirse. No fuerces lo que no fluye. Lo que realmente es para ti llegará con naturalidad y marcará un nuevo comienzo.'},
  {t:'El regalo de la paciencia', m:'La paciencia no retrasa tus sueños; los fortalece. Todo aquello que vale la pena necesita tiempo para crecer. Confía en el proceso, porque el universo nunca olvida aquello que has pedido con el corazón.'},
  {t:'Los ciclos se cumplen', m:'Un ciclo importante está llegando a su fin. Lo que parecía eterno pronto dará paso a una nueva etapa llena de posibilidades. Despide el pasado con gratitud y recibe con confianza lo que comienza.'},
  {t:'La respuesta se acerca', m:'Aquello que has estado esperando está más cerca de lo que imaginas. Muy pronto recibirás una señal, una conversación, una oportunidad o una respuesta que despejará tus dudas. Mantente atento y con el corazón abierto.'},
  {t:'Confía en el camino invisible', m:'Aunque no puedas ver cómo se están acomodando las cosas, el universo continúa trabajando a tu favor. Hay procesos que ocurren en silencio antes de manifestarse. La fe también forma parte del camino.'},
  {t:'El tiempo de recibir', m:'Durante mucho tiempo has dado, aprendido y esperado. Ahora comienza una etapa en la que el universo también quiere entregarte bendiciones. Abre tu corazón para recibir con gratitud lo que está por llegar.'},
  {t:'El universo dice: aún no', m:'Un "todavía no" no significa un "nunca". Hay aspectos que necesitan acomodarse antes de que todo suceda. Confía en que este tiempo de espera tiene un propósito y evitará que recibas algo antes de estar preparado.'},
  {t:'El tiempo de los milagros', m:'Hay momentos en los que la vida cambia de manera inesperada. Lo que parecía imposible encuentra un camino, y aquello que habías perdido comienza a renacer. Mantén viva la esperanza, porque el universo también obra a través de los milagros.'},
  {t:'La calma antes del cambio', m:'Si todo parece tranquilo o incluso detenido, no significa que nada esté ocurriendo. A veces, el universo guarda silencio justo antes de un gran movimiento. Confía, porque el cambio ya viene en camino.'},
  {t:'El destino te está encontrando', m:'No tienes que perseguir aquello que verdaderamente está destinado para ti. Mientras avanzas y creces, eso que tanto anhelas también se acerca a tu vida. Muy pronto ambos caminos se encontrarán.'},
  {t:'Todo madura a su tiempo', m:'Los frutos más valiosos nunca aparecen de un día para otro. Permite que cada experiencia, aprendizaje y oportunidad maduren antes de exigir resultados. Lo que llega en el momento correcto suele permanecer por mucho más tiempo.'},
  {t:'Un nuevo amanecer', m:'Una etapa de mayor claridad está por comenzar. Las dudas se disiparán y comprenderás por qué muchas cosas tuvieron que esperar. El amanecer siempre llega después de la noche más larga.'},
  {t:'La bendición inesperada', m:'El universo puede sorprenderte de formas que jamás imaginaste. No te limites pensando que solo existe un camino para que tus deseos se cumplan. Mantente abierto, porque la vida suele superar tus expectativas.'},
  {t:'La semilla ya germinó', m:'Aunque todavía no puedas verla, aquello que sembraste ya comenzó a crecer. Sigue alimentando tus sueños con confianza y constancia. Lo invisible también forma parte del proceso de manifestación.'},
  {t:'El tiempo de creer', m:'La fe es la fuerza que sostiene los sueños mientras todavía no se manifiestan. No permitas que la duda robe la confianza que has construido. Sigue creyendo, porque el universo responde a los corazones perseverantes.'},
  {t:'Todo tendrá sentido', m:'Llegará el día en que mirarás hacia atrás y comprenderás que cada espera, cada pausa y cada cambio tenían un propósito. Lo que hoy parece confuso, mañana será una de tus mayores enseñanzas.'},
  {t:'La hora ha llegado', m:'Después de tanta preparación, el universo anuncia que un ciclo de espera está por terminar. Es momento de actuar, aceptar oportunidades y confiar en lo que se presenta. Lo que esperabas comienza a manifestarse.'},
  {t:'El regalo del presente', m:'No permitas que la ansiedad por el futuro te robe la belleza del hoy. El presente también contiene regalos, aprendizajes y momentos que un día recordarás con gratitud. Vive plenamente este instante.'},
  {t:'El tiempo de avanzar', m:'El universo te muestra que ya no es momento de esperar, sino de dar el siguiente paso. Confía en tus capacidades y en todo lo que has aprendido. El movimiento abrirá nuevas puertas.'},
  {t:'La recompensa está cerca', m:'Tu esfuerzo, tu paciencia y tu constancia están a punto de dar frutos. No abandones ahora. Lo que tanto has construido comienza a acercarse con fuerza y estabilidad.'},
  {t:'El universo nunca se retrasa', m:'Aunque desde tu perspectiva parezca que todo tarda demasiado, para el universo cada acontecimiento ocurre en el instante preciso. Confía en que nada importante ha pasado de largo; simplemente está llegando en el tiempo ideal.'},
  {t:'El ciclo se completa', m:'Has llegado al final de una etapa importante. Todo lo aprendido, vivido y superado te prepara para comenzar un nuevo capítulo con mayor sabiduría. Celebra tu crecimiento y recibe lo nuevo con el corazón abierto.'},
  {t:'El tiempo perfecto', m:'No existe un mejor momento que aquel que el universo ha preparado para ti. Lo que está destinado a tu vida llegará cuando tu corazón, tu camino y las circunstancias estén alineados. Confía siempre: nada de lo que es para ti puede perderse. Cada espera tiene un propósito y cada bendición encuentra su momento.'}
  ].map(function(c,i){ return { id:i+1, titulo:c.t, mensaje:c.m }; }) }
]};
